name=input("як тебе звати")
print("привіт",name)
age=input("скільки тобі років")
print("мені",age)
film=input("який твій улюблений фільм")
print("мій улюблений фільм",film)
hobby=input("яке твоє хобі")
print("моє хобі",hobby)
country=input("де ти живеш")
print("я живу",country)
